version: '3.7'

networks:
  sub01:
    external: true
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: "192.168.0.0/24"
              gateway: "192.168.0.1"
services:
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: identity_service
      MYSQL_ROOT_PASSWORD: root
    command: 
        - --default-authentication-plugin=mysql_native_password
    networks:
      - sub01
    volumes: 
        - ./init:/docker-entrypoint-initdb.d:ro
        - ./dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer-db:
    image: adminer:4.8.1
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql-db
      ADMINER_DESIGN: hydra
    networks:
      - sub01
    ports:
      - "9080:8080"

  identity-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    restart: always
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/identity_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - sub01

