version: '3.7'

services:
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
      - mysql_db_data_container:/var/lib/mysql

  adminer-db:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql-db
      ADMINER_DESIGN: dracuala
    ports:
      - "9080:8080"

  identity-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/identity_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root


volumes: 
  mysql_db_data_container: 
